name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello World"
      - name: create file
        run: touch ABC.txt
      - name: print goodbye
        run: echo "Done - bye"

       
     
   

     
   
 
